// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AgendaDrawerController from "./agenda_drawer_controller"
application.register("agenda-drawer", AgendaDrawerController)

import AgendaHighlightController from "./agenda_highlight_controller"
application.register("agenda-highlight", AgendaHighlightController)

import AgendaItemController from "./agenda_item_controller"
application.register("agenda-item", AgendaItemController)

import DrawerController from "./drawer_controller"
application.register("drawer", DrawerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PollFrameController from "./poll_frame_controller"
application.register("poll-frame", PollFrameController)

import RecurrenceToggleController from "./recurrence_toggle_controller"
application.register("recurrence-toggle", RecurrenceToggleController)

import SidebarController from "./sidebar_controller"
application.register("sidebar", SidebarController)
